name: "C++ CI/CD"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "tests"
      run: make tests #makefile will auto run test cases
    - name: "build" 
      run: make mainexe #make sures the code compiles with several flags for stricter compilation
    - name: "valgrind install"
      run: sudo apt install -y valgrind
    - name: "run valgrind"
      run:  valgrind ./main 100
